<?php 
namespace PortPontrieuxBundle\Repository;
 
use Doctrine\ORM\QueryBuilder;
 
/**
 * EmplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmplacementRepository extends \Doctrine\ORM\EntityRepository
{
           
            public function mesEmplacementsDQL($em)
            {
                        $req = $em->createQuery('SELECT e FROM PortPontrieuxBundle:Emplacement e');
                        $resultats = $req->getResult();
                       
                        return $resultats;
            }
           
            public function mesEmplacementsQueryBuilder()
            {
                        /*
                        // Méthode 1 : en passant par l'EntityManager
                        $queryBuilder = $this->_em->createQueryBuilder()
                          ->select('e')
                          ->from($this->_entityName, 'e');
                        */
                    
                        // Méthode 2 : en passant par le raccourci (préférable)
                        $queryBuilder = $this->createQueryBuilder('e');
                        // On récupère la Query à partir du QueryBuilder
                        $query = $queryBuilder->getQuery();
                        // On récupère les résultats à partir de la Query
                        $results = $query->getResult();
                        // On retourne ces résultats
                        return $results;
            }
}
